// Code generated by "ohnogen -type=MyFabulousOhNoError -formatbase=16 -output=example_errors.go -ohno"; DO NOT EDIT.

package usage_with_ohno

import (
	"github.com/A-0-5/ohno/pkg/ohno"
	"github.com/A-0-5/ohno/pkg/sourceinfo"
	"strconv"
	"time"
)

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NotFound-100]
	_ = x[AlreadyExists-101]
	_ = x[Internal-102]
	_ = x[Unknown-103]
	_ = x[Busy-104]
	_ = x[Unauthorised-105]
	_ = x[Fatal-106]
}

const (
	_MyFabulousOhNoError_name      = "NotFoundAlreadyExistsInternalUnknownBusyUnauthorisedFatal"
	_MyFabulousOhNoError_desc_name = "I didn't find what you were looking for!I have this already!Its not you, its me :(I don't know what happenedI'm busy rn, can we do this later?You ain't got the creds to do thisHelp!!! Im dying!!!"
)

var (
	_MyFabulousOhNoError_index      = [...]uint8{0, 8, 21, 29, 36, 40, 52, 57}
	_MyFabulousOhNoError_desc_index = [...]uint8{0, 40, 60, 82, 108, 142, 176, 195}
)

// Returns the error name as string
func (i MyFabulousOhNoError) String() string {
	i -= 100
	if i < 0 || i >= MyFabulousOhNoError(len(_MyFabulousOhNoError_index)-1) {
		return "MyFabulousOhNoError(" + strconv.FormatInt(int64(i+100), 10) + ")"
	}
	return _MyFabulousOhNoError_name[_MyFabulousOhNoError_index[i]:_MyFabulousOhNoError_index[i+1]]
}

// Returns the description string
func (i MyFabulousOhNoError) Description() string {
	i -= 100
	if i < 0 || i >= MyFabulousOhNoError(len(_MyFabulousOhNoError_desc_index)-1) {
		return "MyFabulousOhNoError(" + strconv.FormatInt(int64(i+100), 10) + ")"
	}
	return _MyFabulousOhNoError_desc_name[_MyFabulousOhNoError_desc_index[i]:_MyFabulousOhNoError_desc_index[i+1]]
}

// Returns the error's string representation
// [CODE]PACKAGE_NAME.ERROR_NAME: DESCRIPTION
func (i MyFabulousOhNoError) Error() string {
	return "[" + i.Code() + "]" + i.Package() + "." + i.String() + ": " + i.Description()
}

// Returns the package name
func (i MyFabulousOhNoError) Package() string {
	return "usage_with_ohno"
}

// Returns the integer code string as per the format base provided
func (i MyFabulousOhNoError) Code() string {
	return "0x" + strconv.FormatInt(int64(i), 16)
}

// Generate a new error of [ohno.OhNoError] type with the data provided
// timestamp is optional, empty [timestampLayout] will assume default timestamp
// of RFC3339Nano,  if you do not want source information to be captured pass
// [sourceinfo.NoSourceInfo] for the sourceInfoType parameter.
//
// [timestampLayout]: https://pkg.go.dev/time#pkg-constants
func (i MyFabulousOhNoError) OhNo(message string, extra any, cause error, sourceInfoType sourceinfo.SourceInfoType, timestamp time.Time, timestampLayout string) (ohnoError error) {
	return ohno.New(i, message, extra, cause, sourceInfoType, sourceinfo.DefaultCallDepth+1, timestamp, timestampLayout)
}
