// Copyright © A.O.S, 2023.
// All Rights Reserved.
//
// author: A.O.S

// package ohnoer is a package which defines the OhNoer interface. This is a
// generic interface which is implemented by code generated by [ohnogen]
//
// [ohnogen]: https://pkg.go.dev/github.com/A-0-5/ohno/cmd/ohnogen
package ohnoer

// This is an interface type which will provide information about an error
type OhNoer interface {
	String() string
	Description() string
	Error() string
	Package() string
	Code() string
}
